added nose task

diff --git a/tekton/tasks.yaml b/tekton/tasks.yaml
--- a/tekton/tasks.yaml
+++ b/tekton/tasks.yaml
@@ -12,28 +12,38 @@ spec:
   steps:
     - name: echo-message
       image: alpine:3
-      command: [/bin/echo]
+      command: ["/bin/echo"]
       args: ["$(params.message)"]
+
 ---
 apiVersion: tekton.dev/v1beta1
 kind: Task
 metadata:
   name: cleanup
 spec:
-  description: This task will clean up a workspace by deleting all of the files.
+  description: This task will clean up a workspace by deleting all files.
   workspaces:
     - name: source
   steps:
     - name: remove
       image: alpine:3
-      env:
-        - name: WORKSPACE_SOURCE_PATH
-          value: $(workspaces.source.path)
       workingDir: $(workspaces.source.path)
       securityContext:
         runAsNonRoot: false
         runAsUser: 0
-      
+      env:
+        - name: WORKSPACE_SOURCE_PATH
+          value: $(workspaces.source.path)
+      script: |
+        #!/bin/sh
+        set -eu
+        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
+        if [ -d "${WORKSPACE_SOURCE_PATH}" ]; then
+          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
+          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
+          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
+        fi
+
 ---
 apiVersion: tekton.dev/v1beta1
 kind: Task
@@ -45,7 +55,7 @@ spec:
     - name: source
   params:
     - name: args
-      description: Arguments to pass to nose
+      description: Arguments to pass to nosetests
       type: string
       default: "-v"
     - name: database_uri
@@ -62,28 +72,20 @@ spec:
       script: |
         #!/bin/bash
         set -e
-        
-        echo "***** Installing dependencies *****"
-        python -m pip install --upgrade pip wheel
-        pip install -qr requirements.txt
-        
-        echo "***** Running nosetests with: $(params.args)"
-        nosetests $(params.args)
-      
-      script: |
-        #!/usr/bin/env sh
-        set -eu
-        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
-        # Delete any existing contents of the directory if it exists.
-        #
-        # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"
-        # or the root of a mounted volume.
-        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
-          # Delete non-hidden files and directories
+
+        # Cleanup workspace
+        if [ -d "${WORKSPACE_SOURCE_PATH}" ]; then
+          echo "Cleaning workspace..."
           rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
-          # Delete files and directories starting with . but excluding ..
           rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
-          # Delete files and directories starting with .. plus any other character
           rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
         fi
 
+        # Install dependencies
+        echo "***** Installing dependencies *****"
+        python -m pip install --upgrade pip wheel
+        pip install -qr requirements.txt
+
+        # Run nosetests
+        echo "***** Running nosetests with: $(params.args) *****"
+        nosetests $(params.args)
